/**
 * ObjectUI
 * Copyright (c) 2024-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { useEffect, useId, useLayoutEffect, useRef } from 'react';
import type { FormSection } from '@objectstack/spec/ui';
import type { DataSource, FormField, ObjectFormSchema } from '@object-ui/types';
import { Button, Card, CardContent, CardHeader, CardTitle, Checkbox, cn } from '@object-ui/components';
import type { ObjectFormController } from '@object-ui/components';
import { PredicateScopeProvider, usePredicateScope, useSafeFieldLabel } from '@object-ui/react';
import { usePermissions } from '@object-ui/permissions';
import { resolveEffectiveCrudAffordances, resolveFieldRuleState } from '@object-ui/core';
import { LoaderCircle, Plus, Trash2 } from 'lucide-react';
import { ObjectForm } from './ObjectForm';
import { filterAutoGeneratedFields, filterSystemFields } from './autoLayout';
import type { ChildObjectSchemaLike } from './deriveMasterDetail';
import { findRelationshipField } from './deriveMasterDetail';
import { applyFieldPermissions } from './fieldWriteGate';

/** One unsaved child row. `draftKey` is editor identity, never record data. */
export interface RelationshipDraftRow {
  draftKey: string;
  values: Record<string, unknown>;
}

/** Minimal ObjectStack child metadata read by the relationship editor. */
export interface RelationshipObjectSchemaLike extends ChildObjectSchemaLike {
  fields?: Record<string, { type?: string; reference?: string; label?: string; [key: string]: unknown }>;
}

export type RelationshipCollectionMetadataError =
  | { kind: 'missing-relationship'; message: string }
  | { kind: 'missing-field'; fieldName: string; message: string }
  | { kind: 'unsupported-field-type'; fieldName: string; message: string }
  | { kind: 'wrong-reference'; fieldName: string; actualReference?: string; message: string };

export type RelationshipCollectionMetadata =
  | {
      ok: true;
      relationshipField: string;
      /** Declared child fields except the FK filled by the host transaction. */
      fieldNames: string[];
    }
  | { ok: false; error: RelationshipCollectionMetadataError };

/**
 * Resolve and validate the child-to-parent relationship from ObjectStack
 * metadata. `reference` and `type` are the ObjectStack field contract; this
 * helper does not accept aliases or invent relationship declarations.
 */
export function resolveRelationshipCollectionMetadata(
  childSchema: RelationshipObjectSchemaLike | undefined,
  parentObjectName: string,
  explicitRelationshipField?: string,
): RelationshipCollectionMetadata {
  const relationshipField = explicitRelationshipField ?? findRelationshipField(childSchema, parentObjectName);
  if (!relationshipField) {
    return {
      ok: false,
      error: {
        kind: 'missing-relationship',
        message: `No lookup or master_detail field references "${parentObjectName}".`,
      },
    };
  }

  const definition = childSchema?.fields?.[relationshipField];
  if (!definition) {
    return {
      ok: false,
      error: {
        kind: 'missing-field',
        fieldName: relationshipField,
        message: `Field "${relationshipField}" is not declared on the child object.`,
      },
    };
  }

  if (definition.type !== 'lookup' && definition.type !== 'master_detail') {
    return {
      ok: false,
      error: {
        kind: 'unsupported-field-type',
        fieldName: relationshipField,
        message: `Field "${relationshipField}" must be a lookup or master_detail field.`,
      },
    };
  }

  if (definition.reference !== parentObjectName) {
    return {
      ok: false,
      error: {
        kind: 'wrong-reference',
        fieldName: relationshipField,
        actualReference: definition.reference,
        message: `Field "${relationshipField}" references "${definition.reference ?? '(unset)'}", not "${parentObjectName}".`,
      },
    };
  }

  return {
    ok: true,
    relationshipField,
    fieldNames: Object.keys(childSchema?.fields ?? {}).filter((fieldName) => fieldName !== relationshipField),
  };
}

/** Keep draft values within the child metadata field set and exclude its FK. */
export function projectRelationshipDraftValues(
  values: Record<string, unknown>,
  fieldNames: readonly string[],
): Record<string, unknown> {
  const projected: Record<string, unknown> = {};
  for (const fieldName of fieldNames) {
    if (Object.prototype.hasOwnProperty.call(values, fieldName)) {
      projected[fieldName] = values[fieldName];
    }
  }
  return projected;
}

/** Stable identity for a child ObjectForm controller and nested draft group. */
export interface RelationshipDraftRowContext {
  row: RelationshipDraftRow;
  objectName: string;
  objectSchema: RelationshipObjectSchemaLike;
  relationshipField: string;
  /** Register the row's one directly nested collection for aggregate validation. */
  onControllerReady: (controller: RelationshipCollectionEditorController | null) => void;
}

/** A validated row, including any React-composed child collections. */
export interface ValidatedRelationshipDraftRow {
  draftKey: string;
  values: Record<string, unknown>;
  /** Runtime composition output; never an ObjectStack field or persisted column. */
  children: ValidatedRelationshipCollectionDraft[];
}

/** A metadata-resolved relationship draft returned to the outer Save handler. */
export interface ValidatedRelationshipCollectionDraft {
  parentObjectName: string;
  childObjectName: string;
  relationshipField: string;
  rows: ValidatedRelationshipDraftRow[];
}

/** A field or form error located by stable row identity, outermost first. */
export interface RelationshipCollectionValidationError {
  rowKeys: string[];
  objectName: string;
  fieldName?: string;
  message: string;
}

export type RelationshipCollectionValidationResult =
  | { valid: true; draft: ValidatedRelationshipCollectionDraft }
  | {
      valid: false;
      draft?: ValidatedRelationshipCollectionDraft;
      errors: RelationshipCollectionValidationError[];
    };

/** Controller exposed to the host's one-time create/save action. */
export interface RelationshipCollectionEditorController {
  /** Changes whenever local row/controller membership changes. */
  readonly revision: number;
  validate(): Promise<RelationshipCollectionValidationResult>;
}

/** Props for a controlled, in-memory relationship collection editor. */
export interface RelationshipCollectionEditorProps {
  /** Object whose id will be supplied for the child foreign key at host save time. */
  parentObjectName: string;
  /** ObjectStack child object whose rows are edited inline. */
  childObjectName: string;
  /** Child lookup/master_detail field; inferred from ObjectStack metadata when omitted. */
  relationshipField?: string;
  dataSource: DataSource;
  /** Controlled local drafts. `draftKey` is stable UI identity, not record data. */
  value: readonly RelationshipDraftRow[];
  /** Declared child fields to display, in host-selected order. Payload FLS still applies to all draft values. */
  fields?: readonly string[];
  /** Existing ObjectForm section layout to pass to each child row form. */
  sections?: readonly FormSection[];
  /** Existing declared boolean field shown as a main-item checkbox in each card header. */
  primaryField?: string;
  /** Host policy callback after the controlled row receives its primary value. */
  onPrimaryChange?: (draftKey: string, checked: boolean) => void;
  /** Current parent row for child `readonlyWhen` predicates using `parent.*`. */
  parentRecord?: Record<string, unknown>;
  /** Fixed widths for selected row fields; unlisted fields fill remaining space. */
  fieldWidths?: Readonly<Record<string, 112 | 132>>;
  /** Replaces the caller's in-memory draft collection; never persists to a data source. */
  onChange: (rows: RelationshipDraftRow[]) => void;
  /** ObjectForm schema fields remain metadata-driven; this predicate lets the host omit blank rows. */
  includeRow?: (row: RelationshipDraftRow) => boolean;
  /** Host-selected local values for an added row, such as a documented metadata default. */
  createDraftValues?: () => Record<string, unknown>;
  /** Minimum row count enforced by validation. Defaults to zero and never auto-creates rows. */
  minRows?: number;
  /** Additional row-specific removal policy. No confirmation or persisted delete is performed. */
  canRemoveRow?: (row: RelationshipDraftRow, index: number) => boolean;
  /** Whether each included row must register the nested editor rendered by `children`. Defaults to true when the slot is present. */
  nestedEditorRequired?: boolean;
  /** Notifies the host after an immediate local row removal. */
  onRowRemoved?: (row: RelationshipDraftRow) => void;
  /** Receives the collection's aggregate validate-only controller. */
  onControllerReady?: (controller: RelationshipCollectionEditorController | null) => void;
  /** React-only nested collection slot; it is not serialized as FormView metadata. */
  children?: (context: RelationshipDraftRowContext) => React.ReactNode;
  /** React-only row layout; `rows` removes the card shell but keeps the same ObjectForm controls. */
  presentation?: 'cards' | 'rows';
  /** Field grid density used by ObjectForm; `rows` defaults to three columns, capped by field count. */
  columns?: number;
  title?: string;
  itemLabel?: string;
  addLabel?: string;
  removeLabel?: string;
  className?: string;
}

type SchemaLoadState =
  | { key: string; dataSource: DataSource; status: 'ready'; schema: RelationshipObjectSchemaLike }
  | { key: string; dataSource: DataSource; status: 'error'; message: string };

function schemaRequestKey(parentObjectName: string, childObjectName: string, relationshipField?: string): string {
  return `${parentObjectName}\u0000${childObjectName}\u0000${relationshipField ?? ''}`;
}

function fieldGridClasses(columns: number): string {
  const base = 'grid gap-x-[var(--ui-form-column-gap,1rem)] gap-y-[var(--ui-form-row-gap,1rem)]';
  if (columns <= 1) return 'space-y-[var(--ui-form-row-gap,1rem)]';
  if (columns === 2) return `${base} md:grid-cols-2`;
  if (columns === 3) return `${base} md:grid-cols-2 lg:grid-cols-3`;
  return `${base} md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4`;
}

const COMPACT_FIELD_GRID_CLASSES: Readonly<Record<string, { header: string; form: string }>> = {
  '132-112-fill': {
    header: 'grid gap-x-[7px] gap-y-0 grid-cols-1 @md:grid-cols-[132px_112px_minmax(0,1fr)]',
    form: '[&>div]:space-y-[var(--ui-form-row-gap,1rem)] @md:[&>div]:grid @md:[&>div]:grid-cols-[132px_112px_minmax(0,1fr)] @md:[&>div]:gap-x-[7px] @md:[&>div]:gap-y-0 @md:[&>div]:space-y-0',
  },
  '112-132-fill': {
    header: 'grid gap-x-[7px] gap-y-0 grid-cols-1 @md:grid-cols-[112px_132px_minmax(0,1fr)]',
    form: '[&>div]:space-y-[var(--ui-form-row-gap,1rem)] @md:[&>div]:grid @md:[&>div]:grid-cols-[112px_132px_minmax(0,1fr)] @md:[&>div]:gap-x-[7px] @md:[&>div]:gap-y-0 @md:[&>div]:space-y-0',
  },
  '132-fill': {
    header: 'grid gap-x-[7px] gap-y-0 grid-cols-1 @md:grid-cols-[132px_minmax(0,1fr)]',
    form: '[&>div]:space-y-[var(--ui-form-row-gap,1rem)] @md:[&>div]:grid @md:[&>div]:grid-cols-[132px_minmax(0,1fr)] @md:[&>div]:gap-x-[7px] @md:[&>div]:gap-y-0 @md:[&>div]:space-y-0',
  },
  '112-fill': {
    header: 'grid gap-x-[7px] gap-y-0 grid-cols-1 @md:grid-cols-[112px_minmax(0,1fr)]',
    form: '[&>div]:space-y-[var(--ui-form-row-gap,1rem)] @md:[&>div]:grid @md:[&>div]:grid-cols-[112px_minmax(0,1fr)] @md:[&>div]:gap-x-[7px] @md:[&>div]:gap-y-0 @md:[&>div]:space-y-0',
  },
  'fill-132': {
    header: 'grid gap-x-[7px] gap-y-0 grid-cols-1 @md:grid-cols-[minmax(0,1fr)_132px]',
    form: '[&>div]:space-y-[var(--ui-form-row-gap,1rem)] @md:[&>div]:grid @md:[&>div]:grid-cols-[minmax(0,1fr)_132px] @md:[&>div]:gap-x-[7px] @md:[&>div]:gap-y-0 @md:[&>div]:space-y-0',
  },
  'fill-112': {
    header: 'grid gap-x-[7px] gap-y-0 grid-cols-1 @md:grid-cols-[minmax(0,1fr)_112px]',
    form: '[&>div]:space-y-[var(--ui-form-row-gap,1rem)] @md:[&>div]:grid @md:[&>div]:grid-cols-[minmax(0,1fr)_112px] @md:[&>div]:gap-x-[7px] @md:[&>div]:gap-y-0 @md:[&>div]:space-y-0',
  },
  '132-112': {
    header: 'grid gap-x-[7px] gap-y-0 grid-cols-1 @md:grid-cols-[132px_112px]',
    form: '[&>div]:space-y-[var(--ui-form-row-gap,1rem)] @md:[&>div]:grid @md:[&>div]:grid-cols-[132px_112px] @md:[&>div]:gap-x-[7px] @md:[&>div]:gap-y-0 @md:[&>div]:space-y-0',
  },
  '112-132': {
    header: 'grid gap-x-[7px] gap-y-0 grid-cols-1 @md:grid-cols-[112px_132px]',
    form: '[&>div]:space-y-[var(--ui-form-row-gap,1rem)] @md:[&>div]:grid @md:[&>div]:grid-cols-[112px_132px] @md:[&>div]:gap-x-[7px] @md:[&>div]:gap-y-0 @md:[&>div]:space-y-0',
  },
  '132': {
    header: 'grid gap-x-[7px] gap-y-0 grid-cols-1 @md:grid-cols-[132px]',
    form: '[&>div]:space-y-[var(--ui-form-row-gap,1rem)] @md:[&>div]:grid @md:[&>div]:grid-cols-[132px] @md:[&>div]:gap-x-[7px] @md:[&>div]:gap-y-0 @md:[&>div]:space-y-0',
  },
  '112': {
    header: 'grid gap-x-[7px] gap-y-0 grid-cols-1 @md:grid-cols-[112px]',
    form: '[&>div]:space-y-[var(--ui-form-row-gap,1rem)] @md:[&>div]:grid @md:[&>div]:grid-cols-[112px] @md:[&>div]:gap-x-[7px] @md:[&>div]:gap-y-0 @md:[&>div]:space-y-0',
  },
  fill: {
    header: 'grid gap-x-[7px] gap-y-0 grid-cols-1 @md:grid-cols-[minmax(0,1fr)]',
    form: '[&>div]:space-y-[var(--ui-form-row-gap,1rem)] @md:[&>div]:grid @md:[&>div]:grid-cols-[minmax(0,1fr)] @md:[&>div]:gap-x-[7px] @md:[&>div]:gap-y-0 @md:[&>div]:space-y-0',
  },
};

function relationshipFieldGridClass(
  visibleFieldNames: readonly string[],
  fieldWidths: Readonly<Record<string, 112 | 132>> | undefined,
  columns: number | undefined,
): { header: string; form: string } | undefined {
  if (fieldWidths) {
    const signature = visibleFieldNames
      .map((fieldName) => fieldWidths[fieldName] ?? 'fill')
      .join('-');
    return COMPACT_FIELD_GRID_CLASSES[signature];
  }
  return {
    header: fieldGridClasses(Math.min(
    Number.isFinite(columns) ? Math.max(1, Math.floor(columns as number)) : 3,
    Math.max(visibleFieldNames.length, 1),
    )),
    form: '',
  };
}

function sectionMemberName(member: unknown): string | undefined {
  if (typeof member === 'string') return member;
  if (!member || typeof member !== 'object') return undefined;
  const field = member as Record<string, unknown>;
  return typeof field.field === 'string' ? field.field : undefined;
}

function removePrimaryFieldFromSections(
  sections: readonly FormSection[] | undefined,
  primaryField: string | undefined,
): FormSection[] | undefined {
  if (!sections) return undefined;
  if (!primaryField) return [...sections];
  return sections
    .map((section) => Array.isArray(section.fields)
      ? { ...section, fields: section.fields.filter((field) => sectionMemberName(field) !== primaryField) }
      : section)
    .filter((section) => !Array.isArray(section.fields) || section.fields.length > 0 || section.group != null);
}

interface PrimaryFieldRuleContext {
  childObjectName: string;
  primaryField?: string;
  objectSchema: RelationshipObjectSchemaLike | null;
  visibleFieldNames: readonly string[];
  createAllowed: boolean;
  readable: boolean;
  writeDisabled: boolean;
  predicateScope: Record<string, unknown>;
}

function resolvePrimaryFieldState(
  row: RelationshipDraftRow,
  context: PrimaryFieldRuleContext,
): { visible: boolean; readonly: boolean } {
  const { primaryField, objectSchema } = context;
  const definition = primaryField ? objectSchema?.fields?.[primaryField] : undefined;
  if (!primaryField || !definition) return { visible: false, readonly: true };

  const ruleRecord: Record<string, unknown> = {};
  for (const fieldName of context.visibleFieldNames) ruleRecord[fieldName] = null;
  for (const [fieldName, fieldValue] of Object.entries(row.values ?? {})) {
    if (fieldValue !== undefined) ruleRecord[fieldName] = fieldValue;
  }
  const rules = resolveFieldRuleState(
    {
      visibleWhen: definition.visibleWhen as Parameters<typeof resolveFieldRuleState>[0]['visibleWhen'],
      readonlyWhen: definition.readonlyWhen as Parameters<typeof resolveFieldRuleState>[0]['readonlyWhen'],
    },
    ruleRecord,
    { readonly: definition.readonly === true },
    undefined,
    context.predicateScope,
    `field '${primaryField}'`,
  );
  return {
    visible: context.readable && definition.hidden !== true && rules.visible,
    readonly: !context.createAllowed
      || !context.readable
      || context.writeDisabled
      || definition.readonly === true
      || definition.computed === true
      || definition.system === true
      || rules.readonly,
  };
}

/**
 * Controlled inline collection for one metadata-declared child relationship.
 *
 * Every row is rendered by the existing ObjectForm and field registry. Its
 * runtime values are held by the caller, its relationship FK is omitted from
 * the row form, and its submitHandler only collects local values so Enter can
 * never fall through to a generic create/update call. The host's Save action
 * calls the aggregate controller and owns all persistence.
 */
export function RelationshipCollectionEditor({
  parentObjectName,
  childObjectName,
  relationshipField,
  dataSource,
  value,
  fields: selectedFields,
  sections,
  primaryField,
  onPrimaryChange,
  parentRecord,
  fieldWidths,
  onChange,
  includeRow,
  createDraftValues,
  minRows = 0,
  canRemoveRow,
  nestedEditorRequired,
  onRowRemoved,
  onControllerReady,
  children,
  presentation = 'cards',
  columns,
  title = 'Related records',
  itemLabel = 'Record',
  addLabel = 'Add record',
  removeLabel,
  className,
}: RelationshipCollectionEditorProps): React.ReactElement {
  const reactId = useId();
  const nextDraftKey = useRef(0);
  const valuesRef = useRef(value);
  const revisionRef = useRef(0);
  const onChangeRef = useRef(onChange);
  const includeRowRef = useRef(includeRow);
  const formControllers = useRef(new Map<string, ObjectFormController>());
  const nestedControllers = useRef(new Map<string, RelationshipCollectionEditorController>());
  const permissions = usePermissions();
  const { fieldLabel: translateFieldLabel } = useSafeFieldLabel();
  const predicateScope = usePredicateScope();
  const rowPredicateScope = React.useMemo(
    () => parentRecord ? { ...predicateScope, parent: parentRecord } : predicateScope,
    [predicateScope, parentRecord],
  );
  const requestKey = schemaRequestKey(parentObjectName, childObjectName, relationshipField);
  const [loadState, setLoadState] = React.useState<SchemaLoadState | null>(null);

  useLayoutEffect(() => {
    valuesRef.current = value;
    onChangeRef.current = onChange;
    includeRowRef.current = includeRow;
  }, [value, onChange, includeRow]);

  useEffect(() => {
    let active = true;
    Promise.resolve(dataSource.getObjectSchema(childObjectName))
      .then((schema) => {
        if (!active) return;
        if (!schema || typeof schema !== 'object') {
          setLoadState({ key: requestKey, dataSource, status: 'error', message: `No object schema was returned for "${childObjectName}".` });
          return;
        }
        setLoadState({
          key: requestKey,
          dataSource,
          status: 'ready',
          schema: schema as RelationshipObjectSchemaLike,
        });
      })
      .catch((error: unknown) => {
        if (!active) return;
        const message = error instanceof Error ? error.message : String(error);
        setLoadState({ key: requestKey, dataSource, status: 'error', message });
      });
    return () => { active = false; };
  }, [dataSource, childObjectName, requestKey]);

  const currentLoadState =
    loadState?.key === requestKey && loadState.dataSource === dataSource
      ? loadState
      : null;
  const metadata = React.useMemo(
    () => currentLoadState?.status === 'ready'
      ? resolveRelationshipCollectionMetadata(currentLoadState.schema, parentObjectName, relationshipField)
      : null,
    [currentLoadState, parentObjectName, relationshipField],
  );
  const objectSchema = currentLoadState?.status === 'ready' ? currentLoadState.schema : null;
  const resolvedRelationshipField = metadata?.ok ? metadata.relationshipField : null;
  const fieldNames = React.useMemo(() => metadata?.ok ? metadata.fieldNames : [], [metadata]);
  const unknownSelectedField = selectedFields?.find((name) => !fieldNames.includes(name));
  const primaryFieldError = primaryField == null
    ? undefined
    : !fieldNames.includes(primaryField)
      ? `Primary field "${primaryField}" is not a declared child field.`
      : objectSchema?.fields?.[primaryField]?.type !== 'boolean'
        ? `Primary field "${primaryField}" must be a declared boolean field.`
        : undefined;
  const unknownWidthField = Object.keys(fieldWidths ?? {}).find((name) => !fieldNames.includes(name));
  const invalidWidthValue = Object.values(fieldWidths ?? {}).find((width) => width !== 112 && width !== 132);
  const hasFieldWidths = Object.keys(fieldWidths ?? {}).length > 0;
  const fieldWidthsError = primaryField && fieldWidths?.[primaryField] !== undefined
    ? `Primary field "${primaryField}" is rendered in the card header and cannot have a row width.`
    : unknownWidthField
      ? `Width field "${unknownWidthField}" is not a declared child field.`
      : invalidWidthValue !== undefined
        ? 'Row field widths support only 112px and 132px fixed columns.'
        : hasFieldWidths && presentation !== 'rows'
          ? 'Row field widths require the rows presentation.'
          : undefined;
  const formFieldNames = React.useMemo(
    () => (selectedFields ? Array.from(new Set(selectedFields)) : fieldNames)
      .filter((name) => name !== primaryField),
    [selectedFields, fieldNames, primaryField],
  );
  const rowSections = React.useMemo(
    () => removePrimaryFieldFromSections(sections, primaryField),
    [sections, primaryField],
  );
  const visibleFieldNames = React.useMemo(() => {
    if (!objectSchema) return [];
    const fieldPool = formFieldNames.map((name) => ({ name })) as FormField[];
    const readableFields = applyFieldPermissions(fieldPool, {
      perms: permissions,
      objectName: childObjectName,
      mode: 'create',
    }) as FormField[];
    return filterAutoGeneratedFields(
      filterSystemFields(readableFields, objectSchema),
      objectSchema,
    ).map((field) => field.name);
  }, [formFieldNames, objectSchema, permissions, childObjectName]);
  const effectiveMinRows = Number.isFinite(minRows) ? Math.max(0, Math.floor(minRows)) : 0;
  const requiresNestedController = nestedEditorRequired ?? Boolean(children);
  const createAllowed = objectSchema
    ? resolveEffectiveCrudAffordances(
        objectSchema as unknown as Parameters<typeof resolveEffectiveCrudAffordances>[0],
        permissions.getObjectApiOperations(childObjectName),
      ).create && permissions.can(childObjectName, 'create')
    : false;
  const primaryPermissionField = primaryField && objectSchema
    ? applyFieldPermissions([{ name: primaryField } as FormField], {
        perms: permissions,
        objectName: childObjectName,
        mode: 'create',
      })?.[0]
    : undefined;
  const primaryFieldLabel = primaryField && objectSchema?.fields?.[primaryField]
    ? translateFieldLabel(
        childObjectName,
        primaryField,
        objectSchema.fields[primaryField].label || primaryField,
    )
    : undefined;
  const primaryFieldReadable = Boolean(primaryPermissionField);
  const primaryFieldWriteDisabled = primaryPermissionField?.disabled === true;
  const fieldGridLayout = relationshipFieldGridClass(visibleFieldNames, hasFieldWidths ? fieldWidths : undefined, columns);
  const fieldGridClass = fieldGridLayout?.header ?? fieldGridClasses(Math.min(
    Number.isFinite(columns) ? Math.max(1, Math.floor(columns as number)) : 3,
    Math.max(visibleFieldNames.length, 1),
  ));
  const fieldFormClass = hasFieldWidths ? fieldGridLayout?.form : undefined;
  const fieldLayoutError = hasFieldWidths && !fieldWidthsError && !fieldGridLayout
    ? 'The requested row width order is not supported; use an ordered 112px/132px/fill layout with at most three fields.'
    : undefined;

  const observedInputsRef = useRef({
    value,
    includeRow,
    effectiveMinRows,
    createAllowed,
    requiresNestedController,
    primaryField,
    primaryReadable: primaryFieldReadable,
    primaryWriteDisabled: primaryFieldWriteDisabled,
    parentRecord,
    presentation,
    sections,
    visibleFieldNames,
  });
  useLayoutEffect(() => {
    const previous = observedInputsRef.current;
    if (
      previous.value !== value ||
      previous.includeRow !== includeRow ||
      previous.effectiveMinRows !== effectiveMinRows ||
      previous.createAllowed !== createAllowed ||
      previous.requiresNestedController !== requiresNestedController ||
      previous.primaryField !== primaryField ||
      previous.primaryReadable !== primaryFieldReadable ||
      previous.primaryWriteDisabled !== primaryFieldWriteDisabled ||
      previous.parentRecord !== parentRecord ||
      previous.presentation !== presentation ||
      previous.sections !== sections ||
      previous.visibleFieldNames !== visibleFieldNames
    ) {
      revisionRef.current += 1;
    }
    observedInputsRef.current = {
      value,
      includeRow,
      effectiveMinRows,
      createAllowed,
      requiresNestedController,
      primaryField,
      primaryReadable: primaryFieldReadable,
      primaryWriteDisabled: primaryFieldWriteDisabled,
      parentRecord,
      presentation,
      sections,
      visibleFieldNames,
    };
  }, [value, includeRow, effectiveMinRows, createAllowed, requiresNestedController, primaryField, primaryFieldReadable, primaryFieldWriteDisabled, parentRecord, presentation, sections, visibleFieldNames]);

  const replaceRows = (nextRows: RelationshipDraftRow[]) => {
    revisionRef.current += 1;
    valuesRef.current = nextRows;
    onChangeRef.current(nextRows);
  };

  const reportFormController = (draftKey: string, controller: ObjectFormController | null) => {
    if (formControllers.current.get(draftKey) === controller) return;
    revisionRef.current += 1;
    if (controller) formControllers.current.set(draftKey, controller);
    else formControllers.current.delete(draftKey);
  };

  const reportNestedController = (
    draftKey: string,
    controller: RelationshipCollectionEditorController | null,
  ) => {
    if (nestedControllers.current.get(draftKey) === controller) return;
    revisionRef.current += 1;
    if (controller) nestedControllers.current.set(draftKey, controller);
    else nestedControllers.current.delete(draftKey);
  };

  const validationRef = useRef<() => Promise<RelationshipCollectionValidationResult>>(
    async () => ({ valid: false, errors: [{ rowKeys: [], objectName: childObjectName, message: 'The relationship editor is not ready.' }] }),
  );
  const controllerRef = useRef<RelationshipCollectionEditorController | null>(null);
  if (controllerRef.current == null) {
    controllerRef.current = {
      validate: () => validationRef.current(),
      get revision() { return revisionRef.current; },
    };
  }
  const readyCallbackRef = useRef(onControllerReady);
  useLayoutEffect(() => {
    readyCallbackRef.current = onControllerReady;
  }, [onControllerReady]);
  const publishedReadyCallbackRef = useRef<((controller: RelationshipCollectionEditorController | null) => void) | null>(null);
  const hasReadyCallback = onControllerReady != null;
  useLayoutEffect(() => {
    const callback = readyCallbackRef.current;
    if (callback && controllerRef.current) {
      publishedReadyCallbackRef.current = callback;
      callback(controllerRef.current);
    }
    return () => {
      publishedReadyCallbackRef.current?.(null);
      publishedReadyCallbackRef.current = null;
    };
  }, [hasReadyCallback]);

  useLayoutEffect(() => {
    validationRef.current = async () => {
    const validationRevision = revisionRef.current;
    const sourceRows = [...valuesRef.current];
    const nestedControllerSnapshot = new Map(nestedControllers.current);
    const nestedRevisionSnapshot = new Map(
      Array.from(nestedControllerSnapshot, ([draftKey, controller]) => [draftKey, controller.revision] as const),
    );
    if (!currentLoadState) {
      return { valid: false, errors: [{ rowKeys: [], objectName: childObjectName, message: 'Relationship fields are still loading.' }] };
    }
    if (currentLoadState.status === 'error') {
      return { valid: false, errors: [{ rowKeys: [], objectName: childObjectName, message: currentLoadState.message }] };
    }
    if (!metadata?.ok || !resolvedRelationshipField) {
      const message = metadata && !metadata.ok
        ? metadata.error.message
        : 'The relationship metadata is not ready.';
      return { valid: false, errors: [{ rowKeys: [], objectName: childObjectName, message }] };
    }
    if (unknownSelectedField) {
      return { valid: false, errors: [{ rowKeys: [], objectName: childObjectName, fieldName: unknownSelectedField, message: 'A requested field is not declared as an editable child field.' }] };
    }
    if (primaryFieldError) {
      return {
        valid: false,
        errors: [{ rowKeys: [], objectName: childObjectName, fieldName: primaryField, message: primaryFieldError }],
      };
    }
    if (fieldWidthsError) {
      return {
        valid: false,
        errors: [{ rowKeys: [], objectName: childObjectName, fieldName: unknownWidthField, message: fieldWidthsError }],
      };
    }
    if (fieldLayoutError) {
      return {
        valid: false,
        errors: [{ rowKeys: [], objectName: childObjectName, message: fieldLayoutError }],
      };
    }

    const includedRows: RelationshipDraftRow[] = [];
    const includedRowErrors: RelationshipCollectionValidationError[] = [];
    for (const row of sourceRows) {
      try {
        if (includeRowRef.current?.(row) === false) continue;
        includedRows.push(row);
      } catch (error) {
        includedRowErrors.push({
          rowKeys: [row.draftKey],
          objectName: childObjectName,
          message: error instanceof Error ? error.message : 'The row inclusion rule failed.',
        });
      }
    }
    if (includedRowErrors.length > 0) {
      return {
        valid: false,
        draft: {
          parentObjectName,
          childObjectName,
          relationshipField: resolvedRelationshipField,
          rows: [],
        },
        errors: includedRowErrors,
      };
    }
    if (includedRows.length < effectiveMinRows) {
      return {
        valid: false,
        draft: {
          parentObjectName,
          childObjectName,
          relationshipField: resolvedRelationshipField,
          rows: [],
        },
        errors: [{
          rowKeys: [],
          objectName: childObjectName,
          message: `At least ${effectiveMinRows} records are required.`,
      }],
      };
    }
    if (includedRows.length > 0 && !createAllowed) {
      return {
        valid: false,
        draft: {
          parentObjectName,
          childObjectName,
          relationshipField: resolvedRelationshipField,
          rows: [],
        },
        errors: [{
          rowKeys: [],
          objectName: childObjectName,
          message: 'You do not have permission to create records for this object.',
        }],
      };
    }

    const errors: RelationshipCollectionValidationError[] = [];
    const validatedRows: ValidatedRelationshipDraftRow[] = [];
    for (const row of includedRows) {
      let rowValues = projectRelationshipDraftValues(row.values, fieldNames);
      const formController = formControllers.current.get(row.draftKey);
      if (!formController) {
        errors.push({
          rowKeys: [row.draftKey],
          objectName: childObjectName,
          message: `${itemLabel} form is not ready.`,
        });
      } else {
        const rowResult = await formController.validate();
        if (rowResult.valid) {
          rowValues = projectRelationshipDraftValues(rowResult.values, fieldNames);
          if (primaryField && resolvePrimaryFieldState(row, {
            childObjectName,
            primaryField,
            objectSchema,
            visibleFieldNames,
            createAllowed,
            readable: primaryFieldReadable,
            writeDisabled: primaryFieldWriteDisabled,
            predicateScope: rowPredicateScope,
          }).readonly) delete rowValues[primaryField];
        } else {
          for (const [fieldName, message] of Object.entries(rowResult.errors)) {
            errors.push({ rowKeys: [row.draftKey], objectName: childObjectName, fieldName, message });
          }
          if (rowResult.formError) {
            errors.push({ rowKeys: [row.draftKey], objectName: childObjectName, message: rowResult.formError });
          }
        }
      }

      const childDrafts: ValidatedRelationshipCollectionDraft[] = [];
      const nestedController = nestedControllerSnapshot.get(row.draftKey);
      if (nestedController) {
        const nestedResult = await nestedController.validate();
        if (nestedResult.draft) childDrafts.push(nestedResult.draft);
        if (!nestedResult.valid) {
          errors.push(...nestedResult.errors.map((error) => ({
            ...error,
            rowKeys: [row.draftKey, ...error.rowKeys],
          })));
        }
      } else if (requiresNestedController) {
        errors.push({
          rowKeys: [row.draftKey],
          objectName: childObjectName,
          message: 'The nested relationship editor is not ready.',
        });
      }

      validatedRows.push({ draftKey: row.draftKey, values: rowValues, children: childDrafts });
    }

    const draft: ValidatedRelationshipCollectionDraft = {
      parentObjectName,
      childObjectName,
      relationshipField: resolvedRelationshipField,
      rows: validatedRows,
    };
    const nestedChanged = Array.from(nestedControllerSnapshot).some(([draftKey, controller]) =>
      controller.revision !== nestedRevisionSnapshot.get(draftKey),
    );
    if (revisionRef.current !== validationRevision || nestedChanged) {
      errors.push({
        rowKeys: [],
        objectName: childObjectName,
        message: 'Relationship drafts changed while validation was running. Validate again before saving.',
      });
    }
      return errors.length > 0 ? { valid: false, draft, errors } : { valid: true, draft };
    };
  }, [
    currentLoadState,
    metadata,
    resolvedRelationshipField,
    fieldNames,
    unknownSelectedField,
    effectiveMinRows,
    requiresNestedController,
    createAllowed,
    primaryField,
    objectSchema,
    visibleFieldNames,
    primaryFieldReadable,
    primaryFieldWriteDisabled,
    rowPredicateScope,
    primaryFieldError,
    fieldWidthsError,
    fieldLayoutError,
    unknownWidthField,
    parentObjectName,
    childObjectName,
    itemLabel,
  ]);

  if (!currentLoadState) {
    return (
      <section className={cn('space-y-3', className)} aria-busy="true" data-testid="relationship-collection-loading">
        <h3 className="text-sm font-medium">{title}</h3>
        <p className="flex items-center gap-2 text-sm text-muted-foreground" role="status">
          <LoaderCircle className="size-4 animate-spin" aria-hidden="true" />
          Loading relationship fields…
        </p>
      </section>
    );
  }

  if (currentLoadState.status === 'error' || !metadata?.ok || !objectSchema || !resolvedRelationshipField || unknownSelectedField || primaryFieldError || fieldWidthsError || fieldLayoutError) {
    const message = currentLoadState.status === 'error'
      ? `Could not load fields for ${childObjectName}: ${currentLoadState.message}`
      : unknownSelectedField
        ? `Field "${unknownSelectedField}" is not declared as an editable child field.`
        : primaryFieldError
          ? primaryFieldError
          : fieldWidthsError
            ? fieldWidthsError
            : fieldLayoutError
              ? fieldLayoutError
              : metadata && !metadata.ok
                ? metadata.error.message
                : `No lookup or master_detail field references "${parentObjectName}".`;
    return (
      <section className={cn('space-y-3', className)} aria-labelledby={`${reactId}-title`}>
        <h3 id={`${reactId}-title`} className="text-sm font-medium">{title}</h3>
        <p className="text-sm text-destructive" role="alert" data-testid="relationship-collection-error">{message}</p>
      </section>
    );
  }

  const addRow = () => {
    const draftKey = `${reactId}-row-${nextDraftKey.current++}`;
    const initialValues = createDraftValues?.() ?? {};
    const row: RelationshipDraftRow = {
      draftKey,
      values: projectRelationshipDraftValues(initialValues, fieldNames),
    };
    replaceRows([...valuesRef.current, row]);
  };

  const removeRow = (row: RelationshipDraftRow) => {
    const nextRows = valuesRef.current.filter((candidate) => candidate.draftKey !== row.draftKey);
    formControllers.current.delete(row.draftKey);
    nestedControllers.current.delete(row.draftKey);
    replaceRows(nextRows);
    onRowRemoved?.(row);
  };

  const changePrimary = (draftKey: string, checked: boolean) => {
    if (!primaryField) return;
    const row = value.find((candidate) => candidate.draftKey === draftKey);
    if (!row) return;
    const state = resolvePrimaryFieldState(row, {
      childObjectName,
      primaryField,
      objectSchema,
      visibleFieldNames,
      createAllowed,
      readable: primaryFieldReadable,
      writeDisabled: primaryFieldWriteDisabled,
      predicateScope: rowPredicateScope,
    });
    if (!state.visible || state.readonly) return;
    onChange(value.map((candidate) => candidate.draftKey === draftKey
      ? {
          ...candidate,
          values: projectRelationshipDraftValues({
            ...candidate.values,
            [primaryField]: checked,
          }, fieldNames),
        }
      : candidate));
    onPrimaryChange?.(draftKey, checked);
  };

  return (
    <section className={cn('space-y-3', hasFieldWidths && presentation === 'rows' && '@container', className)} aria-labelledby={`${reactId}-title`} data-testid="relationship-collection">
      <div className="flex items-center justify-between gap-3">
        <h3 id={`${reactId}-title`} className="text-sm font-medium">{title}</h3>
        <Button type="button" size="sm" variant="outline" onClick={addRow} disabled={!createAllowed}>
          <Plus className="mr-1.5 size-4" aria-hidden="true" />
          {addLabel}
        </Button>
      </div>
      {!createAllowed && (
        <p className="text-sm text-muted-foreground" role="status">
          Record creation is unavailable for this object.
        </p>
      )}
          {value.length === 0 ? (
            <p className="text-sm text-muted-foreground">No records added.</p>
          ) : (
            <div className={presentation === 'rows' ? 'space-y-0' : 'space-y-3'}>
          {presentation === 'rows' && visibleFieldNames.length > 0 && (
            <div
              className={cn(
                hasFieldWidths
                  ? 'grid grid-cols-[minmax(0,1fr)_34px] items-end gap-x-[7px] border-b border-border px-2.5 pb-1 text-xs font-medium text-muted-foreground'
                  : 'grid grid-cols-[minmax(0,1fr)_auto] items-end gap-x-2 border-b border-border pb-1 text-xs font-medium text-muted-foreground',
              )}
              data-testid="relationship-column-header"
              aria-hidden="true"
            >
              <div className={fieldGridClass}>
                {visibleFieldNames.map((fieldName) => {
                  const fallback = objectSchema.fields?.[fieldName]?.label || fieldName;
                  return (
                    <span key={fieldName} className="truncate">
                      {translateFieldLabel(childObjectName, fieldName, fallback)}
                    </span>
                  );
                })}
              </div>
              <span className="sr-only">{removeLabel ?? 'Remove'}</span>
            </div>
          )}
          {value.map((row, index) => {
            const rowTitle = `${itemLabel} ${index + 1}`;
            const primaryState = resolvePrimaryFieldState(row, {
              childObjectName,
              primaryField,
              objectSchema,
              visibleFieldNames,
              createAllowed,
              readable: primaryFieldReadable,
              writeDisabled: primaryFieldWriteDisabled,
              predicateScope: rowPredicateScope,
            });
            const rowColumns = Number.isFinite(columns)
              ? Math.min(Math.max(1, Math.floor(columns as number)), Math.max(visibleFieldNames.length, 1))
              : presentation === 'rows'
                ? Math.min(3, Math.max(visibleFieldNames.length, 1))
                : undefined;
            const rowSchema: ObjectFormSchema = {
              type: 'object-form',
              objectName: childObjectName,
              mode: 'create',
              formType: 'simple',
              fields: formFieldNames,
              // The existing ObjectForm section normalizer consumes the spec's
              // `field` member shape; this cast bridges its narrower authoring type.
              sections: rowSections as unknown as ObjectFormSchema['sections'],
              columns: hasFieldWidths ? 1 : rowColumns,
              className: cn(
                presentation === 'rows' && '[&_label]:sr-only',
                hasFieldWidths && fieldFormClass,
              ),
              showSubmit: false,
              showCancel: false,
              showReset: false,
              submitHandler: (submitted) => {
                // Enter may submit this inner form; collect only its local values.
                // The explicit host Save remains the sole persistence boundary.
                onChange(value.map((candidate) =>
                  candidate.draftKey === row.draftKey
                    ? { ...candidate, values: projectRelationshipDraftValues({ ...candidate.values, ...projectRelationshipDraftValues(submitted, fieldNames) }, fieldNames) }
                    : candidate,
                ));
              },
            };
            const removeDisabled = canRemoveRow ? !canRemoveRow(row, index) : false;
            const rowId = `${reactId}-${encodeURIComponent(row.draftKey)}`;
            const nestedContent = children?.({
              row,
              objectName: childObjectName,
              objectSchema,
              relationshipField: resolvedRelationshipField,
              onControllerReady: (controller) => reportNestedController(row.draftKey, controller),
            });
            const rowForm = (
              <ObjectForm
                key={`${childObjectName}:${row.draftKey}`}
                schema={rowSchema}
                dataSource={dataSource}
                values={projectRelationshipDraftValues(row.values, fieldNames)}
                onValuesChange={(nextValues) => {
                  onChange(value.map((candidate) =>
                    candidate.draftKey === row.draftKey
                      ? { ...candidate, values: projectRelationshipDraftValues({ ...candidate.values, ...projectRelationshipDraftValues(nextValues, fieldNames) }, fieldNames) }
                      : candidate,
                  ));
                }}
                onControllerReady={(controller) => reportFormController(row.draftKey, controller)}
              />
            );
            const removeButton = (
              <Button
                type="button"
                size="sm"
                variant="ghost"
                className={presentation === 'rows'
                  ? cn('w-[34px] shrink-0 p-0', hasFieldWidths && 'h-[var(--ui-icon-button-size,2rem)]')
                  : undefined}
                onClick={() => removeRow(row)}
                disabled={removeDisabled}
                aria-label={`${removeLabel ?? 'Remove'} ${rowTitle}`}
              >
                <Trash2 className={presentation === 'rows' ? 'size-4' : 'mr-1 size-4'} aria-hidden="true" />
                <span className={presentation === 'rows' ? 'sr-only' : undefined}>{removeLabel ?? 'Remove'}</span>
              </Button>
            );

            if (presentation === 'rows') {
              return (
                <div
                  key={row.draftKey}
                  className={cn(
                    hasFieldWidths
                      ? 'grid grid-cols-[minmax(0,1fr)_34px] items-start gap-x-[7px] border-border px-2.5 py-[8.75px]'
                      : 'grid grid-cols-[minmax(0,1fr)_34px] items-start gap-x-2 border-border p-2.5',
                    index > 0 && 'border-t',
                  )}
                  data-testid="relationship-draft-row"
                  data-row-key={row.draftKey}
                  role="group"
                  aria-label={rowTitle}
                >
                  <div className="min-w-0 space-y-2">
                    <PredicateScopeProvider scope={rowPredicateScope}>
                      {rowForm}
                      {nestedContent}
                    </PredicateScopeProvider>
                  </div>
                  {removeButton}
                </div>
              );
            }

            return (
              <Card key={row.draftKey} className="shadow-none" data-testid="relationship-draft-row" data-row-key={row.draftKey}>
                <CardHeader className="flex flex-row items-center justify-between gap-3 space-y-0 p-3">
                  <CardTitle id={`${rowId}-title`} className="text-sm font-medium">{rowTitle}</CardTitle>
                  {primaryField && primaryFieldLabel && primaryPermissionField && primaryState.visible && (
                    <div className="flex min-w-0 items-center gap-2" data-testid="relationship-primary-control">
                      <Checkbox
                        checked={row.values?.[primaryField] === true}
                        onCheckedChange={(checked) => changePrimary(row.draftKey, checked === true)}
                        disabled={primaryState.readonly}
                        aria-label={primaryFieldLabel}
                        data-testid={`relationship-primary-${encodeURIComponent(row.draftKey)}`}
                      />
                      <span className="truncate text-sm text-muted-foreground">{primaryFieldLabel}</span>
                    </div>
                  )}
                  {removeButton}
                </CardHeader>
                <CardContent className="space-y-4 p-3 pt-0" aria-labelledby={`${rowId}-title`}>
                  <PredicateScopeProvider scope={rowPredicateScope}>
                    {rowForm}
                    {nestedContent}
                  </PredicateScopeProvider>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </section>
  );
}
